{{- if .Values.tlsInternal.enabled }}
---
# Certificate for governor-api
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.api.name }}-cert
  labels:
    app: {{ .Values.api.name }}
spec:
  secretName: {{ .Values.api.name }}-tls
  duration: {{ .Values.tlsInternal.certificates.duration }}
  renewBefore: {{ .Values.tlsInternal.certificates.renewBefore }}
  privateKey:
    algorithm: {{ .Values.tlsInternal.certificates.privateKey.algorithm }}
    size: {{ .Values.tlsInternal.certificates.privateKey.size }}
    encoding: {{ .Values.tlsInternal.certificates.privateKey.encoding }}
  usages:
    - server auth
    - client auth
  {{- if .Values.api.tlsInternal.certificate }}
  {{- with .Values.api.tlsInternal.certificate.commonName }}
  commonName: {{ . }}
  {{- end }}
  {{- end }}
  dnsNames:
    {{- if and .Values.api.tlsInternal.certificate .Values.api.tlsInternal.certificate.dnsNames }}
    {{- toYaml .Values.api.tlsInternal.certificate.dnsNames | nindent 4 }}
    {{- else }}
    - {{ .Values.api.name }}.{{ .Release.Namespace }}.svc.cluster.local
    {{- end }}
  issuerRef:
    name: {{ .Values.tlsInternal.certificates.issuerRef.name }}
    kind: {{ .Values.tlsInternal.certificates.issuerRef.kind }}
---
# Certificate for governor-front
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.front.name }}-cert
  labels:
    app: {{ .Values.front.name }}
spec:
  secretName: {{ .Values.front.name }}-tls
  duration: {{ .Values.tlsInternal.certificates.duration }}
  renewBefore: {{ .Values.tlsInternal.certificates.renewBefore }}
  privateKey:
    algorithm: {{ .Values.tlsInternal.certificates.privateKey.algorithm }}
    size: {{ .Values.tlsInternal.certificates.privateKey.size }}
    encoding: {{ .Values.tlsInternal.certificates.privateKey.encoding }}
  usages:
    - server auth
    - client auth
  {{- if .Values.front.tlsInternal.certificate }}
  {{- with .Values.front.tlsInternal.certificate.commonName }}
  commonName: {{ . }}
  {{- end }}
  {{- end }}
  dnsNames:
    {{- if and .Values.front.tlsInternal.certificate .Values.front.tlsInternal.certificate.dnsNames }}
    {{- toYaml .Values.front.tlsInternal.certificate.dnsNames | nindent 4 }}
    {{- else }}
    - {{ .Values.front.name }}.{{ .Release.Namespace }}.svc.cluster.local
    {{- end }}
  issuerRef:
    name: {{ .Values.tlsInternal.certificates.issuerRef.name }}
    kind: {{ .Values.tlsInternal.certificates.issuerRef.kind }}
---
# Certificate for governor-agent
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.agent.name }}-cert
  labels:
    app: {{ .Values.agent.name }}
spec:
  secretName: {{ .Values.agent.name }}-tls
  duration: {{ .Values.tlsInternal.certificates.duration }}
  renewBefore: {{ .Values.tlsInternal.certificates.renewBefore }}
  privateKey:
    algorithm: {{ .Values.tlsInternal.certificates.privateKey.algorithm }}
    size: {{ .Values.tlsInternal.certificates.privateKey.size }}
    encoding: {{ .Values.tlsInternal.certificates.privateKey.encoding }}
  usages:
    - client auth
  {{- if .Values.agent.tlsInternal.certificate }}
  {{- with .Values.agent.tlsInternal.certificate.commonName }}
  commonName: {{ . }}
  {{- end }}
  {{- end }}
  dnsNames:
    {{- if and .Values.agent.tlsInternal.certificate .Values.agent.tlsInternal.certificate.dnsNames }}
    {{- toYaml .Values.agent.tlsInternal.certificate.dnsNames | nindent 4 }}
    {{- else }}
    - {{ .Values.agent.name }}.{{ .Release.Namespace }}.svc.cluster.local
    {{- end }}
  issuerRef:
    name: {{ .Values.tlsInternal.certificates.issuerRef.name }}
    kind: {{ .Values.tlsInternal.certificates.issuerRef.kind }}
{{- end }}
