{{- if .Values.tlsInternal.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.front.name }}-envoy-config
  labels:
    app: {{ .Values.front.name }}
data:
  envoy.yaml: |
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: {{ .Values.tlsInternal.ports.admin }}

    static_resources:
      listeners:
        # HTTPS inbound listener (from ingress/external)
        - name: https_inbound
          address:
            socket_address:
              address: 0.0.0.0
              port_value: {{ .Values.tlsInternal.ports.secureHttp }}
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: https_inbound
                    codec_type: AUTO
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: local_service
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: local_http
                    http_filters:
                      {{- include "governor.envoy.httpRouter" . | nindent 22 }}
              {{- include "governor.envoy.downstreamTls" . | nindent 14 }}

        # Egress listener for api HTTP (front connects here, envoy does TLS to api)
        - name: api_http_egress
          address:
            socket_address:
              address: 127.0.0.1
              port_value: {{ .Values.tlsInternal.ports.egressHttp }}
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: api_http_egress
                    codec_type: AUTO
                    http_protocol_options:
                      accept_http_10: true
                    route_config:
                      name: api_route
                      virtual_hosts:
                        - name: api_service
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: api_https
                    http_filters:
                      {{- include "governor.envoy.httpRouter" . | nindent 22 }}

        {{- include "governor.envoy.apiGrpcEgressListener" (dict "egressGrpcPort" .Values.tlsInternal.ports.egressGrpc) | nindent 8 }}

      clusters:
        # Local HTTP backend (front container)
        - name: local_http
          type: STATIC
          connect_timeout: 5s
          load_assignment:
            cluster_name: local_http
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: {{ .Values.front.container.port }}

        # Outbound to api HTTPS (with TLS)
        - name: api_https
          type: STRICT_DNS
          connect_timeout: 5s
          load_assignment:
            cluster_name: api_https
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: {{ .Values.api.name }}
                          port_value: {{ .Values.api.service.port }}
          {{- include "governor.envoy.upstreamTls" . | nindent 10 }}

        {{- include "governor.envoy.apiGrpcsCluster" (dict "apiName" .Values.api.name "apiGrpcPort" .Values.api.service.grpcPort) | nindent 8 }}
{{- end }}