{{- if .Values.envoy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.api.name }}-envoy-config
  labels:
    app: {{ .Values.api.name }}
data:
  envoy.yaml: |
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: {{ .Values.envoy.ports.admin }}

    static_resources:
      listeners:
        # HTTPS inbound listener (for front -> api HTTP calls)
        - name: https_inbound
          address:
            socket_address:
              address: 0.0.0.0
              port_value: {{ .Values.envoy.ports.secureHttp }}
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: https_inbound
                    codec_type: AUTO
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: local_service
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: local_http
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              transport_socket:
                name: envoy.transport_sockets.tls
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
                  require_client_certificate: true
                  common_tls_context:
                    tls_certificates:
                      - certificate_chain:
                          filename: /etc/envoy/certs/tls.crt
                        private_key:
                          filename: /etc/envoy/certs/tls.key
                    validation_context:
                      trusted_ca:
                        filename: /etc/envoy/ca/ca.crt

        # gRPCS inbound listener (for agent -> api and front -> api gRPC calls)
        - name: grpcs_inbound
          address:
            socket_address:
              address: 0.0.0.0
              port_value: {{ .Values.envoy.ports.secureGrpc }}
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: grpcs_inbound
                    codec_type: HTTP2
                    route_config:
                      name: grpc_route
                      virtual_hosts:
                        - name: grpc_service
                          domains: ["*"]
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: local_grpc
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              transport_socket:
                name: envoy.transport_sockets.tls
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
                  require_client_certificate: true
                  common_tls_context:
                    tls_certificates:
                      - certificate_chain:
                          filename: /etc/envoy/certs/tls.crt
                        private_key:
                          filename: /etc/envoy/certs/tls.key
                    validation_context:
                      trusted_ca:
                        filename: /etc/envoy/ca/ca.crt

      clusters:
        # Local HTTP backend (api container)
        - name: local_http
          type: STATIC
          connect_timeout: 5s
          load_assignment:
            cluster_name: local_http
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: {{ .Values.api.container.port }}

        # Local gRPC backend (api container)
        - name: local_grpc
          type: STATIC
          connect_timeout: 5s
          http2_protocol_options: {}
          load_assignment:
            cluster_name: local_grpc
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: {{ .Values.api.container.grpcPort }}
{{- end }}
