{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.name }}-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | b64enc | quote }}
{{- end }}
