apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  labels:
    group: {{ .Values.api.group }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: {{ .Values.api.name }}
  ports:
    {{- if .Values.envoy.enabled }}
    # When Envoy is enabled, route through secure ports
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.envoy.ports.secureHttp }}
      name: https
    - port: {{ .Values.api.service.grpcPort }}
      targetPort: {{ .Values.envoy.ports.secureGrpc }}
      name: grpcs
    {{- else }}
    # Original plaintext ports
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.container.port }}
      name: defaultport
    - port: {{ .Values.api.service.grpcPort }}
      targetPort: {{ .Values.api.container.grpcPort }}
      name: grpcport
    {{- end }}
